### ISSUE TITLE
Configure multiple accounts as transfer sources/destinations

### ISSUE THREAD

**Issue by DewaldV** [DewaldV/finops-monzo#6]
Each Credit card transaction can be funded from either a personal or joint account. The incoming CSV will contain a `source` field that will define where the funds for a given transaction should come from, either `joint` or `personal`.

The `destination` for the funds will differ based on the `source` so either the incoming CSV will need to have both `source` and `destination` or, more likely, we can configure a map of `source -> destination` for the CLI to use.

```toml
[destinations.personal]
account = "998877665"
source = "personal"

[destinations.joint]
account = "112233445"
source = "joint"
```

This kind of configuration could provide lots of flexibility for routing to different destinations from a given source based on other metadata as well.

```toml
# default destination
[destinations.personal]
account = "998877665"
source = "personal"

# override for above destination if category = "gaming"
[destinations.personal.gaming]
account = "998877665"
source = "personal"
category = "gaming"
```
